### PR TITLE
Add FixEvolutionGlitch to base patches

### PR DESCRIPTION
**Pull request by Chesyon**
Will only be applied to US ROMs, because the patch doesn't exist for other regions.

### CODE REVIEW

**Comment by theCapypara** [comment]
Hi! Have you tested this? I think is_applied throws an exception if it's not supported. See how the ExpandPokeList patch is applied.

**Comment by theCapypara** [comment]
Ah didn't see the second part on mobile without scrolling. I think the way it's done for ExpandPokeList would still be better, even though I guess it's unlikely this patch will ever be compatible with another reason, since it's not needed.

**Comment by Chesyon** [comment]
Updated to now use the same implementation as ExpandPokeList (to the best of my ability.)

**Review by theCapypara — APPROVED** [review]
Thanks

**Pull request merged**
